# Generated by Django 5.1.4 on 2024-12-28 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='avaliacao',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
